1). Consider that email IDs are supposed to be for the following format:
username@website.extension.
Here, there are three conditions to keep in mind:
1. The username can only contain characters 0-9, a-z and A-Z.
2. The website name can contain only characters a-z
3. The extension can have 2 or 3 alphabets(a-z).

Given an email ID, you have to determine if it is valid or not.

Sample Input:
prerna@upgrad.com

Sample Output:
valid

In [2]:
import re

def checkmail(email):
    pattern = r'^[0-9a-zA-Z]+@[a-z]+\.[a-z]{2,3}$'

    # Use the re.match() function to check if the email matches the pattern
    if re.match(pattern, email):
        return "valid"
    else:
        return "invalid"

email=input()

print(checkmail(email))






abhi@ref.ci
valid


2).  Given a nested list, write python code to flatten the list.
Note: The input list will strictly have 2 levels, i.e. the list will be of the form [[1,2],[3,4]]. Inputs like [1,[2,3]] and [[1,[2,3],4],5] are not applicable.

For example: If the input list is :
[[1,2,3],[4,5],[6,7,8,9]]
Then the output should be:
[1,2,3,4,5,6,7,8,9]

In [11]:
import numpy as np

# Read the input string from the user
input_str = input()

# Create a NumPy array from the nested list
input_list = np.array(input_str)

flat_list = [element for sublist in input_list for element in sublist]

print(flat_list)


[[1,2,3],[4,5],[6,7,8,9]]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


3). Given a list of positive integers, you have to find numbers divisible by 3 and replace them with their squares.
For example, consider the list below:
Input: [1,2,3,4,5,6]
The output for the above list would be: [1,2,9,4,5,36]. Because 3 and 6 were divisible by 3, these numbers were replaced with their squares.

In [21]:
import numpy as np

# Read the input string from the user
input_str = input()

# Use eval to evaluate the input string and create a list.    ----->> CHECK EVAL()
input_list = eval(input_str)

# Convert the list into a NumPy array
input_array = np.array(input_list)

# Use a lambda function to square the number if it's divisible by 3, otherwise leave it unchanged
output = list(map(lambda x: x * x if x % 3 == 0 else x, input_array))

# Print the result
print(output)


[1,2,3,4,5,6]
[1, 2, 9, 4, 5, 36]


4).  Write a program that computes the value of n+nn+nnn+nnnn with a given digit as the value of n.
For example, if n=9 , then you have to find the value of 9+99+999+9999.

In [46]:
n = int(input())

def sum_special(n,p):
  total_sum = 0
  for i in range(0,p):
    total_sum += n*pow(10,i)
  return total_sum


sum_out = sum_special(n,1) + sum_special(n,2) + sum_special(n,3) + sum_special(n,4)

print(sum_out)




9
11106


5).  Given a string, you have to find the first n most frequent characters in it.
You have to print the three letters in alphabetically sorted order.
The input will contain two lines, the first line will contain a string and the second line will contain the letter n.
The output should be a list of n most frequent letters in alphabetically sorted order.
Note: If there are two letters with the same frequency, then the alphabetically preceding alphabet should be picked first. (For example, in "aabbccc", if n=2, then output list would have c and a.)
Sample Input:
ddddaacccb
3
Sample Output:
['a', 'c', 'd']

In the above example, the order of frequencies is : d>c>a>b
Here, d,c and a are three most frequent characters which are displayed in alphabetically sorted order.

In [2]:
# Read the input string
input_str = input().strip()

# Read the value of n
n = int(input())

# Create a dictionary to store character frequencies
char_freq = {}

# Calculate character frequencies
for char in input_str:
    char_freq[char] = char_freq.get(char, 0) + 1

# Sort the characters by frequency and then alphabetically
sorted_chars = sorted(char_freq.keys(), key=lambda char: (-char_freq[char], char))

# Extract the first n characters
result = sorted_chars[:n]

# Sort the result alphabetically
result.sort()

# Print the result as a list
print(result)


kjashdjahdskhadksjaksdamd
3
['a', 'd', 'k']


6).  Write Python code which takes 2 numbers x and y as input and generates a 2-dimensional numpy array where value in the i-th row and j-th column of the array should be (i+j)/2.
Note: i=0,1,...x-1 and j=0,1....,y-1
The input will have two lines with x and y respectively.
The output should be a 2D numpy array.
Sample Input:
3
4
Sample Output:

[[0.  0.5 1.  1.5]
 [0.5 1.  1.5 2. ]
 [1.  1.5 2.  2.5]]

In [9]:
import numpy as np

x=int(input())
y=int(input())
#write your code here

a = np.zeros((x,y))

for i in range(0,x):
    for j in range(0,y):
        a[i,j]=(i+j)/2

print(a)

3
4
[[0.  0.5 1.  1.5]
 [0.5 1.  1.5 2. ]
 [1.  1.5 2.  2.5]]
